# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\python_worksapce\geonaivateur2\GeonavigateurF6.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1715, 1042)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(50, 0))
        MainWindow.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/logoAppli.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(100, 500))
        self.widget.setMaximumSize(QtCore.QSize(1677, 1677))
        self.widget.setStyleSheet(_fromUtf8("background-color: rgb(208, 239, 255);"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(5, 20, 0, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.bouton_accueil = QtGui.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.bouton_accueil.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/hom2.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bouton_accueil.setIcon(icon1)
        self.bouton_accueil.setIconSize(QtCore.QSize(30, 50))
        self.bouton_accueil.setObjectName(_fromUtf8("bouton_accueil"))
        self.verticalLayout.addWidget(self.bouton_accueil)
        self.commandLinkButton_2 = QtGui.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        self.commandLinkButton_2.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/map.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_2.setIcon(icon2)
        self.commandLinkButton_2.setIconSize(QtCore.QSize(30, 40))
        self.commandLinkButton_2.setObjectName(_fromUtf8("commandLinkButton_2"))
        self.verticalLayout.addWidget(self.commandLinkButton_2)
        self.commandLinkButton_5 = QtGui.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        self.commandLinkButton_5.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("images/satellite.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_5.setIcon(icon3)
        self.commandLinkButton_5.setIconSize(QtCore.QSize(30, 30))
        self.commandLinkButton_5.setObjectName(_fromUtf8("commandLinkButton_5"))
        self.verticalLayout.addWidget(self.commandLinkButton_5)
        self.commandLinkButton_6 = QtGui.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(9)
        self.commandLinkButton_6.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("images/historique.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_6.setIcon(icon4)
        self.commandLinkButton_6.setIconSize(QtCore.QSize(30, 30))
        self.commandLinkButton_6.setObjectName(_fromUtf8("commandLinkButton_6"))
        self.verticalLayout.addWidget(self.commandLinkButton_6)
        self.commandLinkButton_4 = QtGui.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        self.commandLinkButton_4.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("images/courbe.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_4.setIcon(icon5)
        self.commandLinkButton_4.setIconSize(QtCore.QSize(30, 30))
        self.commandLinkButton_4.setObjectName(_fromUtf8("commandLinkButton_4"))
        self.verticalLayout.addWidget(self.commandLinkButton_4)
        self.commandLinkButton_8 = QtGui.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        self.commandLinkButton_8.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("images/cloud_computing.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_8.setIcon(icon6)
        self.commandLinkButton_8.setIconSize(QtCore.QSize(30, 40))
        self.commandLinkButton_8.setObjectName(_fromUtf8("commandLinkButton_8"))
        self.verticalLayout.addWidget(self.commandLinkButton_8)
        self.commandLinkButton_3 = QtGui.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI"))
        font.setPointSize(10)
        self.commandLinkButton_3.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("images/reglage2.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_3.setIcon(icon7)
        self.commandLinkButton_3.setIconSize(QtCore.QSize(30, 40))
        self.commandLinkButton_3.setObjectName(_fromUtf8("commandLinkButton_3"))
        self.verticalLayout.addWidget(self.commandLinkButton_3)
        self.horizontalLayout.addWidget(self.widget)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(1500, 16777215))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.accueil = QtGui.QWidget()
        self.accueil.setObjectName(_fromUtf8("accueil"))
        self.gridLayout_2 = QtGui.QGridLayout(self.accueil)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_accueil = QtGui.QLabel(self.accueil)
        self.label_accueil.setText(_fromUtf8(""))
        self.label_accueil.setPixmap(QtGui.QPixmap(_fromUtf8("images/accueil4.png")))
        self.label_accueil.setScaledContents(True)
        self.label_accueil.setObjectName(_fromUtf8("label_accueil"))
        self.gridLayout_2.addWidget(self.label_accueil, 0, 0, 1, 1)
        self.tabWidget.addTab(self.accueil, _fromUtf8(""))
        self.trame = QtGui.QWidget()
        self.trame.setObjectName(_fromUtf8("trame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.trame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.trames_text = QtGui.QTextEdit(self.trame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trames_text.setFont(font)
        self.trames_text.setObjectName(_fromUtf8("trames_text"))
        self.verticalLayout_4.addWidget(self.trames_text)
        self.tabWidget.addTab(self.trame, _fromUtf8(""))
        self.map = QtGui.QWidget()
        self.map.setObjectName(_fromUtf8("map"))
        self.gridLayout = QtGui.QGridLayout(self.map)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.echelle_sliderH = QtGui.QSlider(self.map)
        self.echelle_sliderH.setMaximum(1500)
        self.echelle_sliderH.setProperty("value", 500)
        self.echelle_sliderH.setOrientation(QtCore.Qt.Horizontal)
        self.echelle_sliderH.setObjectName(_fromUtf8("echelle_sliderH"))
        self.gridLayout.addWidget(self.echelle_sliderH, 2, 2, 1, 1)
        self.matplotlibwidget = MatplotlibWidget(self.map)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibwidget.sizePolicy().hasHeightForWidth())
        self.matplotlibwidget.setSizePolicy(sizePolicy)
        self.matplotlibwidget.setMinimumSize(QtCore.QSize(1400, 400))
        self.matplotlibwidget.setMaximumSize(QtCore.QSize(167772, 1677))
        self.matplotlibwidget.setAutoFillBackground(False)
        self.matplotlibwidget.setObjectName(_fromUtf8("matplotlibwidget"))
        self.gridLayout.addWidget(self.matplotlibwidget, 1, 2, 1, 1)
        self.echelle_sliderV = QtGui.QSlider(self.map)
        self.echelle_sliderV.setMinimum(0)
        self.echelle_sliderV.setMaximum(1500)
        self.echelle_sliderV.setProperty("value", 1150)
        self.echelle_sliderV.setOrientation(QtCore.Qt.Vertical)
        self.echelle_sliderV.setInvertedAppearance(True)
        self.echelle_sliderV.setInvertedControls(False)
        self.echelle_sliderV.setObjectName(_fromUtf8("echelle_sliderV"))
        self.gridLayout.addWidget(self.echelle_sliderV, 1, 0, 1, 1)
        self.tabWidget.addTab(self.map, _fromUtf8(""))
        self.Constellation = QtGui.QWidget()
        self.Constellation.setObjectName(_fromUtf8("Constellation"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Constellation)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.matplotlibwidget_2 = MatplotlibWidget(self.Constellation)
        self.matplotlibwidget_2.setObjectName(_fromUtf8("matplotlibwidget_2"))
        self.verticalLayout_3.addWidget(self.matplotlibwidget_2)
        self.tabWidget.addTab(self.Constellation, _fromUtf8(""))
        self.Vitesse = QtGui.QWidget()
        self.Vitesse.setObjectName(_fromUtf8("Vitesse"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.Vitesse)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.matplotlibwidget_3 = MatplotlibWidget(self.Vitesse)
        self.matplotlibwidget_3.setObjectName(_fromUtf8("matplotlibwidget_3"))
        self.verticalLayout_9.addWidget(self.matplotlibwidget_3)
        self.tabWidget.addTab(self.Vitesse, _fromUtf8(""))
        self.onlineFiles = QtGui.QWidget()
        self.onlineFiles.setObjectName(_fromUtf8("onlineFiles"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.onlineFiles)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.treeWidget = QtGui.QTreeWidget(self.onlineFiles)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setDragDropOverwriteMode(True)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setIconSize(QtCore.QSize(10, 10))
        self.treeWidget.setAllColumnsShowFocus(True)
        self.treeWidget.setWordWrap(True)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("images/imagesVM4W7IT2.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.treeWidget.headerItem().setIcon(0, icon8)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setMinimumSectionSize(200)
        self.horizontalLayout_2.addWidget(self.treeWidget)
        self.textEdit_2 = QtGui.QTextEdit(self.onlineFiles)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.horizontalLayout_2.addWidget(self.textEdit_2)
        self.tabWidget.addTab(self.onlineFiles, _fromUtf8(""))
        self.historique = QtGui.QWidget()
        self.historique.setObjectName(_fromUtf8("historique"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.historique)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.textEdit = QtGui.QTextEdit(self.historique)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_8.addWidget(self.textEdit)
        self.tabWidget.addTab(self.historique, _fromUtf8(""))
        self.documentation = QtGui.QWidget()
        self.documentation.setObjectName(_fromUtf8("documentation"))
        self.tabWidget.addTab(self.documentation, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.reglage = QtGui.QWidget()
        self.reglage.setObjectName(_fromUtf8("reglage"))
        self.label_2 = QtGui.QLabel(self.reglage)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_6 = QtGui.QLineEdit(self.reglage)
        self.lineEdit_6.setGeometry(QtCore.QRect(320, 70, 401, 31))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.label_5 = QtGui.QLabel(self.reglage)
        self.label_5.setGeometry(QtCore.QRect(80, 150, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_8 = QtGui.QLineEdit(self.reglage)
        self.lineEdit_8.setGeometry(QtCore.QRect(320, 140, 401, 31))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.label_3 = QtGui.QLabel(self.reglage)
        self.label_3.setGeometry(QtCore.QRect(80, 220, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboBox_3 = QtGui.QComboBox(self.reglage)
        self.comboBox_3.setGeometry(QtCore.QRect(320, 210, 411, 41))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.reglage)
        self.label_4.setGeometry(QtCore.QRect(80, 300, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.comboBox_4 = QtGui.QComboBox(self.reglage)
        self.comboBox_4.setGeometry(QtCore.QRect(320, 290, 411, 41))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.reglage)
        self.label_6.setGeometry(QtCore.QRect(70, 380, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.comboBox_5 = QtGui.QComboBox(self.reglage)
        self.comboBox_5.setGeometry(QtCore.QRect(320, 370, 411, 41))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.enregistrerReglage = QtGui.QCommandLinkButton(self.reglage)
        self.enregistrerReglage.setGeometry(QtCore.QRect(130, 610, 225, 48))
        self.enregistrerReglage.setStyleSheet(_fromUtf8(""))
        self.enregistrerReglage.setObjectName(_fromUtf8("enregistrerReglage"))
        self.annulerReglage = QtGui.QCommandLinkButton(self.reglage)
        self.annulerReglage.setGeometry(QtCore.QRect(520, 620, 225, 48))
        self.annulerReglage.setObjectName(_fromUtf8("annulerReglage"))
        self.tabWidget.addTab(self.reglage, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.line_rechercheAdresse = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_rechercheAdresse.sizePolicy().hasHeightForWidth())
        self.line_rechercheAdresse.setSizePolicy(sizePolicy)
        self.line_rechercheAdresse.setMinimumSize(QtCore.QSize(300, 0))
        self.line_rechercheAdresse.setStyleSheet(_fromUtf8(""))
        self.line_rechercheAdresse.setObjectName(_fromUtf8("line_rechercheAdresse"))
        self.lineEdit = QtGui.QLineEdit(self.line_rechercheAdresse)
        self.lineEdit.setGeometry(QtCore.QRect(10, 330, 241, 41))
        self.lineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.commandLinkButton_7 = QtGui.QCommandLinkButton(self.line_rechercheAdresse)
        self.commandLinkButton_7.setGeometry(QtCore.QRect(250, 330, 41, 41))
        self.commandLinkButton_7.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/hp/Pictures/IMAGES/loupe.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_7.setIcon(icon9)
        self.commandLinkButton_7.setObjectName(_fromUtf8("commandLinkButton_7"))
        self.etiquette_donneesActuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.etiquette_donneesActuelle.setGeometry(QtCore.QRect(20, 10, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.etiquette_donneesActuelle.setFont(font)
        self.etiquette_donneesActuelle.setObjectName(_fromUtf8("etiquette_donneesActuelle"))
        self.deco = QtGui.QLabel(self.line_rechercheAdresse)
        self.deco.setGeometry(QtCore.QRect(20, 40, 250, 2))
        self.deco.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.deco.setText(_fromUtf8(""))
        self.deco.setObjectName(_fromUtf8("deco"))
        self.label_latitude_actuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_latitude_actuelle.setGeometry(QtCore.QRect(30, 110, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_latitude_actuelle.setFont(font)
        self.label_latitude_actuelle.setObjectName(_fromUtf8("label_latitude_actuelle"))
        self.label_longitude_actuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_longitude_actuelle.setGeometry(QtCore.QRect(30, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_longitude_actuelle.setFont(font)
        self.label_longitude_actuelle.setObjectName(_fromUtf8("label_longitude_actuelle"))
        self.label_vitesse_actuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_vitesse_actuelle.setGeometry(QtCore.QRect(30, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_vitesse_actuelle.setFont(font)
        self.label_vitesse_actuelle.setObjectName(_fromUtf8("label_vitesse_actuelle"))
        self.label_distance_actuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_distance_actuelle.setGeometry(QtCore.QRect(30, 200, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_distance_actuelle.setFont(font)
        self.label_distance_actuelle.setObjectName(_fromUtf8("label_distance_actuelle"))
        self.label_distance_actuelle_2 = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_distance_actuelle_2.setGeometry(QtCore.QRect(30, 230, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_distance_actuelle_2.setFont(font)
        self.label_distance_actuelle_2.setObjectName(_fromUtf8("label_distance_actuelle_2"))
        self.deco_2 = QtGui.QLabel(self.line_rechercheAdresse)
        self.deco_2.setGeometry(QtCore.QRect(0, 320, 300, 2))
        self.deco_2.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.deco_2.setText(_fromUtf8(""))
        self.deco_2.setObjectName(_fromUtf8("deco_2"))
        self.label_longitude_actuelle_2 = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_longitude_actuelle_2.setGeometry(QtCore.QRect(10, 510, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_longitude_actuelle_2.setFont(font)
        self.label_longitude_actuelle_2.setObjectName(_fromUtf8("label_longitude_actuelle_2"))
        self.label_latitude_actuelle_3 = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_latitude_actuelle_3.setGeometry(QtCore.QRect(10, 460, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_latitude_actuelle_3.setFont(font)
        self.label_latitude_actuelle_3.setObjectName(_fromUtf8("label_latitude_actuelle_3"))
        self.lat_depart = QtGui.QLineEdit(self.line_rechercheAdresse)
        self.lat_depart.setGeometry(QtCore.QRect(90, 450, 191, 41))
        self.lat_depart.setObjectName(_fromUtf8("lat_depart"))
        self.long_depart = QtGui.QLineEdit(self.line_rechercheAdresse)
        self.long_depart.setGeometry(QtCore.QRect(90, 500, 191, 41))
        self.long_depart.setObjectName(_fromUtf8("long_depart"))
        self.etiquette_donneesActuelle_2 = QtGui.QLabel(self.line_rechercheAdresse)
        self.etiquette_donneesActuelle_2.setGeometry(QtCore.QRect(10, 410, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.etiquette_donneesActuelle_2.setFont(font)
        self.etiquette_donneesActuelle_2.setObjectName(_fromUtf8("etiquette_donneesActuelle_2"))
        self.adresse_depart = QtGui.QLineEdit(self.line_rechercheAdresse)
        self.adresse_depart.setGeometry(QtCore.QRect(20, 680, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.adresse_depart.setFont(font)
        self.adresse_depart.setObjectName(_fromUtf8("adresse_depart"))
        self.adresse_arrivee = QtGui.QLineEdit(self.line_rechercheAdresse)
        self.adresse_arrivee.setGeometry(QtCore.QRect(20, 730, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.adresse_arrivee.setFont(font)
        self.adresse_arrivee.setObjectName(_fromUtf8("adresse_arrivee"))
        self.comboBox = QtGui.QComboBox(self.line_rechercheAdresse)
        self.comboBox.setGeometry(QtCore.QRect(100, 790, 171, 31))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("images/Sports-Walking-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon10, _fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("images/images.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon11, _fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("images/voiture.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon12, _fromUtf8(""))
        self.label_longitude_actuelle_3 = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_longitude_actuelle_3.setGeometry(QtCore.QRect(20, 800, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_longitude_actuelle_3.setFont(font)
        self.label_longitude_actuelle_3.setObjectName(_fromUtf8("label_longitude_actuelle_3"))
        self.label_latitude_actuelle_4 = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_latitude_actuelle_4.setGeometry(QtCore.QRect(10, 580, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_latitude_actuelle_4.setFont(font)
        self.label_latitude_actuelle_4.setObjectName(_fromUtf8("label_latitude_actuelle_4"))
        self.label_longitude_actuelle_4 = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_longitude_actuelle_4.setGeometry(QtCore.QRect(10, 640, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_longitude_actuelle_4.setFont(font)
        self.label_longitude_actuelle_4.setObjectName(_fromUtf8("label_longitude_actuelle_4"))
        self.long_arrivee = QtGui.QLineEdit(self.line_rechercheAdresse)
        self.long_arrivee.setGeometry(QtCore.QRect(90, 630, 191, 41))
        self.long_arrivee.setObjectName(_fromUtf8("long_arrivee"))
        self.lat_arrivee = QtGui.QLineEdit(self.line_rechercheAdresse)
        self.lat_arrivee.setGeometry(QtCore.QRect(90, 560, 191, 41))
        self.lat_arrivee.setObjectName(_fromUtf8("lat_arrivee"))
        self.itineraireModecheckBox = QtGui.QCheckBox(self.line_rechercheAdresse)
        self.itineraireModecheckBox.setGeometry(QtCore.QRect(100, 410, 81, 20))
        self.itineraireModecheckBox.setText(_fromUtf8(""))
        self.itineraireModecheckBox.setObjectName(_fromUtf8("itineraireModecheckBox"))
        self.ValeurlatitudeActuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.ValeurlatitudeActuelle.setGeometry(QtCore.QRect(100, 110, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ValeurlatitudeActuelle.setFont(font)
        self.ValeurlatitudeActuelle.setObjectName(_fromUtf8("ValeurlatitudeActuelle"))
        self.Valeurlongitude_actuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.Valeurlongitude_actuelle.setGeometry(QtCore.QRect(100, 150, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Valeurlongitude_actuelle.setFont(font)
        self.Valeurlongitude_actuelle.setObjectName(_fromUtf8("Valeurlongitude_actuelle"))
        self.Valeurvitesse_actuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.Valeurvitesse_actuelle.setGeometry(QtCore.QRect(110, 170, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Valeurvitesse_actuelle.setFont(font)
        self.Valeurvitesse_actuelle.setObjectName(_fromUtf8("Valeurvitesse_actuelle"))
        self.Valeurdistance_actuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.Valeurdistance_actuelle.setGeometry(QtCore.QRect(110, 200, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Valeurdistance_actuelle.setFont(font)
        self.Valeurdistance_actuelle.setObjectName(_fromUtf8("Valeurdistance_actuelle"))
        self.Valeurduree = QtGui.QLabel(self.line_rechercheAdresse)
        self.Valeurduree.setGeometry(QtCore.QRect(110, 230, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Valeurduree.setFont(font)
        self.Valeurduree.setObjectName(_fromUtf8("Valeurduree"))
        self.label_latitude_actuelle_2 = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_latitude_actuelle_2.setGeometry(QtCore.QRect(30, 260, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_latitude_actuelle_2.setFont(font)
        self.label_latitude_actuelle_2.setObjectName(_fromUtf8("label_latitude_actuelle_2"))
        self.label_latitude_actuelle_5 = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_latitude_actuelle_5.setGeometry(QtCore.QRect(30, 290, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_latitude_actuelle_5.setFont(font)
        self.label_latitude_actuelle_5.setObjectName(_fromUtf8("label_latitude_actuelle_5"))
        self.label_latitude_actuelle_6 = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_latitude_actuelle_6.setGeometry(QtCore.QRect(30, 80, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_latitude_actuelle_6.setFont(font)
        self.label_latitude_actuelle_6.setObjectName(_fromUtf8("label_latitude_actuelle_6"))
        self.ValeurlheureActuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.ValeurlheureActuelle.setGeometry(QtCore.QRect(100, 80, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ValeurlheureActuelle.setFont(font)
        self.ValeurlheureActuelle.setObjectName(_fromUtf8("ValeurlheureActuelle"))
        self.label_latitude_actuelle_7 = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_latitude_actuelle_7.setGeometry(QtCore.QRect(30, 50, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_latitude_actuelle_7.setFont(font)
        self.label_latitude_actuelle_7.setObjectName(_fromUtf8("label_latitude_actuelle_7"))
        self.ValeurldateActuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.ValeurldateActuelle.setGeometry(QtCore.QRect(100, 50, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ValeurldateActuelle.setFont(font)
        self.ValeurldateActuelle.setObjectName(_fromUtf8("ValeurldateActuelle"))
        self.label_duree_trajet = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_duree_trajet.setGeometry(QtCore.QRect(30, 850, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_duree_trajet.setFont(font)
        self.label_duree_trajet.setObjectName(_fromUtf8("label_duree_trajet"))
        self.duree_trajet = QtGui.QLabel(self.line_rechercheAdresse)
        self.duree_trajet.setGeometry(QtCore.QRect(110, 850, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.duree_trajet.setFont(font)
        self.duree_trajet.setObjectName(_fromUtf8("duree_trajet"))
        self.validerIti = QtGui.QPushButton(self.line_rechercheAdresse)
        self.validerIti.setGeometry(QtCore.QRect(40, 890, 241, 28))
        self.validerIti.setObjectName(_fromUtf8("validerIti"))
        self.label_vdop_actuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_vdop_actuelle.setGeometry(QtCore.QRect(90, 260, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_vdop_actuelle.setFont(font)
        self.label_vdop_actuelle.setObjectName(_fromUtf8("label_vdop_actuelle"))
        self.label_hdop_actuelle = QtGui.QLabel(self.line_rechercheAdresse)
        self.label_hdop_actuelle.setGeometry(QtCore.QRect(90, 290, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_hdop_actuelle.setFont(font)
        self.label_hdop_actuelle.setObjectName(_fromUtf8("label_hdop_actuelle"))
        self.horizontalLayout.addWidget(self.line_rechercheAdresse)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1715, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPorts = QtGui.QMenu(self.menubar)
        self.menuPorts.setObjectName(_fromUtf8("menuPorts"))
        self.menuA_propos = QtGui.QMenu(self.menubar)
        self.menuA_propos.setObjectName(_fromUtf8("menuA_propos"))
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName(_fromUtf8("menuAide"))
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menuAnalyse = QtGui.QMenu(self.menubar)
        self.menuAnalyse.setObjectName(_fromUtf8("menuAnalyse"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOUVRIR = QtGui.QAction(MainWindow)
        self.actionOUVRIR.setObjectName(_fromUtf8("actionOUVRIR"))
        self.actionCOM1 = QtGui.QAction(MainWindow)
        self.actionCOM1.setCheckable(True)
        self.actionCOM1.setEnabled(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("images/USB-Logo-Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCOM1.setIcon(icon13)
        self.actionCOM1.setObjectName(_fromUtf8("actionCOM1"))
        self.actionCOM4 = QtGui.QAction(MainWindow)
        self.actionCOM4.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/hp/Pictures/USB-Logo-Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCOM4.setIcon(icon14)
        self.actionCOM4.setObjectName(_fromUtf8("actionCOM4"))
        self.actionCOM2 = QtGui.QAction(MainWindow)
        self.actionCOM2.setCheckable(True)
        self.actionCOM2.setEnabled(False)
        self.actionCOM2.setIcon(icon13)
        self.actionCOM2.setObjectName(_fromUtf8("actionCOM2"))
        self.actionOuvrir = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("images/file-2-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOuvrir.setIcon(icon15)
        self.actionOuvrir.setObjectName(_fromUtf8("actionOuvrir"))
        self.actionR_cents = QtGui.QAction(MainWindow)
        self.actionR_cents.setIcon(icon4)
        self.actionR_cents.setObjectName(_fromUtf8("actionR_cents"))
        self.actionEnregister = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("images/39-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnregister.setIcon(icon16)
        self.actionEnregister.setObjectName(_fromUtf8("actionEnregister"))
        self.actionCOM3 = QtGui.QAction(MainWindow)
        self.actionCOM3.setCheckable(True)
        self.actionCOM3.setEnabled(False)
        self.actionCOM3.setIcon(icon13)
        self.actionCOM3.setObjectName(_fromUtf8("actionCOM3"))
        self.actionAuteurs = QtGui.QAction(MainWindow)
        self.actionAuteurs.setObjectName(_fromUtf8("actionAuteurs"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionAuteurs_2 = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/hp/Pictures/tete-chauve-avec-le-symbole-du-droit-d-39-auteur-et-bouee-de-sauvetage-a-l-39-interieur_318-49272.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAuteurs_2.setIcon(icon17)
        self.actionAuteurs_2.setObjectName(_fromUtf8("actionAuteurs_2"))
        self.actionLancer = QtGui.QAction(MainWindow)
        self.actionLancer.setCheckable(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("images/application_go_run-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLancer.setIcon(icon18)
        self.actionLancer.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionLancer.setObjectName(_fromUtf8("actionLancer"))
        self.actionArreter = QtGui.QAction(MainWindow)
        self.actionArreter.setCheckable(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("images/icone-valori3.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionArreter.setIcon(icon19)
        self.actionArreter.setObjectName(_fromUtf8("actionArreter"))
        self.menuPorts.addAction(self.actionCOM1)
        self.menuPorts.addSeparator()
        self.menuPorts.addAction(self.actionCOM2)
        self.menuPorts.addAction(self.actionCOM3)
        self.menuA_propos.addAction(self.actionAuteurs_2)
        self.menuAide.addAction(self.actionDocumentation)
        self.menuFichier.addAction(self.actionOuvrir)
        self.menuFichier.addAction(self.actionR_cents)
        self.menuFichier.addAction(self.actionEnregister)
        self.menuAnalyse.addAction(self.actionLancer)
        self.menuAnalyse.addAction(self.actionArreter)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuPorts.menuAction())
        self.menubar.addAction(self.menuAnalyse.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())
        self.menubar.addAction(self.menuA_propos.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Géojoc", None))
        self.bouton_accueil.setText(_translate("MainWindow", "Accueil", None))
        self.commandLinkButton_2.setText(_translate("MainWindow", "Map", None))
        self.commandLinkButton_5.setText(_translate("MainWindow", "Satellites", None))
        self.commandLinkButton_6.setText(_translate("MainWindow", "Historique", None))
        self.commandLinkButton_4.setText(_translate("MainWindow", "courbes", None))
        self.commandLinkButton_8.setText(_translate("MainWindow", "Online Files", None))
        self.commandLinkButton_3.setText(_translate("MainWindow", "Régleages", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.accueil), _translate("MainWindow", "Accueil", None))
        self.trames_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">TRAMES NMEA</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trame), _translate("MainWindow", "Trames ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.map), _translate("MainWindow", "Map", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Constellation), _translate("MainWindow", "Constellation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Vitesse), _translate("MainWindow", "vitesse", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "geonav", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.onlineFiles), _translate("MainWindow", "Fichiers en ligne", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.historique), _translate("MainWindow", "Historique", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documentation), _translate("MainWindow", "documentation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page", None))
        self.label_2.setText(_translate("MainWindow", "Sauvegarde:", None))
        self.label_5.setText(_translate("MainWindow", "Dossier:", None))
        self.label_3.setText(_translate("MainWindow", "Débit :", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "4800", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "9600", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "115000", None))
        self.label_4.setText(_translate("MainWindow", "Pages de démarrage", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Acceuil", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Map", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Courbe de vitesse", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Trames", None))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Historique", None))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "Fihciers en ligne ", None))
        self.label_6.setText(_translate("MainWindow", "Couleur de la courbe ", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Vert", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Rouge", None))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Bleu", None))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "Marron", None))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "Orange", None))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "Fihciers en ligne ", None))
        self.enregistrerReglage.setText(_translate("MainWindow", "ENRESITRER", None))
        self.annulerReglage.setText(_translate("MainWindow", "ANNULER", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reglage), _translate("MainWindow", "Réglage", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Rechercher", None))
        self.etiquette_donneesActuelle.setText(_translate("MainWindow", "Données Actuelles", None))
        self.label_latitude_actuelle.setText(_translate("MainWindow", "Latitude:", None))
        self.label_longitude_actuelle.setText(_translate("MainWindow", "Longitude:", None))
        self.label_vitesse_actuelle.setText(_translate("MainWindow", "Vitesse:", None))
        self.label_distance_actuelle.setText(_translate("MainWindow", "Distance:", None))
        self.label_distance_actuelle_2.setText(_translate("MainWindow", "Durée:", None))
        self.label_longitude_actuelle_2.setText(_translate("MainWindow", "Longitude:", None))
        self.label_latitude_actuelle_3.setText(_translate("MainWindow", "Latitude:", None))
        self.lat_depart.setPlaceholderText(_translate("MainWindow", "Lat départ", None))
        self.long_depart.setPlaceholderText(_translate("MainWindow", "long de départ", None))
        self.etiquette_donneesActuelle_2.setText(_translate("MainWindow", "Itinéraire", None))
        self.adresse_depart.setPlaceholderText(_translate("MainWindow", "Adresse départ", None))
        self.adresse_arrivee.setPlaceholderText(_translate("MainWindow", "Adresse destination", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "marche", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "vélo", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "voiture", None))
        self.label_longitude_actuelle_3.setText(_translate("MainWindow", "transport", None))
        self.label_latitude_actuelle_4.setText(_translate("MainWindow", "Latitude:", None))
        self.label_longitude_actuelle_4.setText(_translate("MainWindow", "Longitude:", None))
        self.long_arrivee.setPlaceholderText(_translate("MainWindow", "long arrivée", None))
        self.lat_arrivee.setPlaceholderText(_translate("MainWindow", "Lat arrivée", None))
        self.ValeurlatitudeActuelle.setText(_translate("MainWindow", "------------------", None))
        self.Valeurlongitude_actuelle.setText(_translate("MainWindow", "--------------------", None))
        self.Valeurvitesse_actuelle.setText(_translate("MainWindow", "0 m/s", None))
        self.Valeurdistance_actuelle.setText(_translate("MainWindow", "0 m", None))
        self.Valeurduree.setText(_translate("MainWindow", "0 s", None))
        self.label_latitude_actuelle_2.setText(_translate("MainWindow", "VDOP:", None))
        self.label_latitude_actuelle_5.setText(_translate("MainWindow", "HDOP:", None))
        self.label_latitude_actuelle_6.setText(_translate("MainWindow", "Heure:", None))
        self.ValeurlheureActuelle.setText(_translate("MainWindow", "hh:mm:ss", None))
        self.label_latitude_actuelle_7.setText(_translate("MainWindow", "Date:", None))
        self.ValeurldateActuelle.setText(_translate("MainWindow", "jj/mm/aaaa", None))
        self.label_duree_trajet.setText(_translate("MainWindow", "durée", None))
        self.duree_trajet.setText(_translate("MainWindow", "0s", None))
        self.validerIti.setText(_translate("MainWindow", "Valider", None))
        self.label_vdop_actuelle.setText(_translate("MainWindow", "---", None))
        self.label_hdop_actuelle.setText(_translate("MainWindow", "---", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.menuPorts.setTitle(_translate("MainWindow", "Ports", None))
        self.menuA_propos.setTitle(_translate("MainWindow", "A propos", None))
        self.menuAide.setTitle(_translate("MainWindow", "Aide", None))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier", None))
        self.menuAnalyse.setTitle(_translate("MainWindow", "Analyse", None))
        self.actionOUVRIR.setText(_translate("MainWindow", "OUVRIR", None))
        self.actionCOM1.setText(_translate("MainWindow", "COM3", None))
        self.actionCOM4.setText(_translate("MainWindow", "COM4", None))
        self.actionCOM2.setText(_translate("MainWindow", "COM5", None))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir", None))
        self.actionOuvrir.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionR_cents.setText(_translate("MainWindow", "Récents", None))
        self.actionEnregister.setText(_translate("MainWindow", "Enregister", None))
        self.actionEnregister.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionCOM3.setText(_translate("MainWindow", "COM6", None))
        self.actionAuteurs.setText(_translate("MainWindow", "Auteurs", None))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation", None))
        self.actionAuteurs_2.setText(_translate("MainWindow", "auteurs", None))
        self.actionLancer.setText(_translate("MainWindow", "Lancer", None))
        self.actionLancer.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.actionArreter.setText(_translate("MainWindow", "Arreter", None))
        self.actionArreter.setShortcut(_translate("MainWindow", "Esc", None))

from matplotlibwidget import MatplotlibWidget
